spring:
  application:
    name: innobank

  datasource:
    url: jdbc:postgresql://localhost:5432/innobank
    username: myuser
    password: secret

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  
  docker:
    compose:
      lifecycle-management: start_only

  flyway: 
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

  # sql:
  #   init: --> no need for this compose up creates the db automatically use this to create other databases for example for keycloak
  #     mode: always
  #     schema-locations: classpath:init.sql